add_newline = false

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '

[golang]
format = '[ $version ](bold cyan)'

[docker_context]
symbol = ""
style = "bold blue"

[kubernetes]
symbol = '☸ '
disabled = true
detect_files = ['Dockerfile']
format = '[$symbol$context( \($namespace\))]($style) '
