theme = "github_dark"

[editor]
true-color = true
line-number = "relative"
mouse = false
default-yank-register = "+"
clipboard-provider = "pasteboard"
end-of-line-diagnostics = "hint"
bufferline = "multiple"

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "error"

[editor.lsp]
display-progress-messages = true
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.auto-save]
focus-lost = true

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true

[editor.indent-guides]
render = true
character = "▏"
skip-levels = 1

[editor.whitespace.render]
space = "all"
tab = "all"
nbsp = "none"
nnbsp = "none"
newline = "none"

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name", "file-modification-indicator"]
right = [
  "diagnostics",
  "version-control",
  "position",
  "file-encoding",
  "file-line-ending",
  "file-type",
]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.normal]
"C-s" = ":write!"
"C-j" = "save_selection"
"C-x" = ":reset-diff-change"
"C-f" = ":format"

[keys.normal.space]
"q" = { "q" = ":quit-all", s = ":write-quit-all!", f = ":quit-all!" }
"space" = "file_picker"
"b" = { f = "buffer_picker", q = ":buffer-close", o = ":buffer-close-others", s = ":write-buffer-close" }

[keys.insert]
"j" = { j = "normal_mode" }
"C-l" = "move_char_right"
