"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Luca Fondo"
email = "luca.fondo@trai.ch"

[signing]
behavior = "drop"
backend = "ssh"
key = "Git Signing Key"

[git]
sign-on-push = true
