[tools]
go = "1.25"
"go:github.com/docker/docker-language-server/cmd/docker-language-server" = "0.12.0"
"go:github.com/go-delve/delve/cmd/dlv" = "1.25.0"
"go:golang.org/x/tools/gopls" = "0.19.1"
node = "24.2.0"

[settings]
experimental = true
