[tools]
go = "1.25"
"go:github.com/docker/docker-language-server/cmd/docker-language-server" = "0.12.0"
"go:github.com/go-delve/delve/cmd/dlv" = "1.25.0"
"go:golang.org/x/tools/gopls" = "0.19.1"
java = "temurin-21.0.5+11.0.LTS"
node = "24.2.0"
python = "3.13.3"
rust = "stable"
yarn = "4.9.2"

[settings]
experimental = true
